version: "3"

services:
  jenkins:
    env_file:
      - '.env'
    image: 'jenkins/jenkins'
    ports:
      - '8080:8080'
    volumes:
      - jenkins_data:/var/jenkins_home

volumes: 
  jenkins_data: